### ISSUE TITLE
烧录固件大小大于openart本身的rom大小

### ISSUE THREAD

**Issue by zhengbaiyang** [Y1ZzLu/openart_fw_18th#2]
烧录固件大小13M，而openartmini本身只有4M的rom，烧录时报错，改变启动设备类型到sd卡烧录后报错文件起始链接位置无效，是什么情况
![屏幕截图 2024-04-14 204754](https://github.com/Y1ZzLu/openart_fw_18th/assets/109739963/cce92433-6fa9-42d1-b3d5-3c6c7cbed97f)
![屏幕截图 2024-04-14 204918](https://github.com/Y1ZzLu/openart_fw_18th/assets/109739963/1af47802-3b66-436b-8d63-17a5b03fc515)

**Comment by Y1ZzLu** [comment]
先确认一下硬件版本是否为v2.0以下版本，并严格按照烧录办法.md操作
如果仍然报错，建议退回更老版本的烧录工具
关于为什么13mb的固件能烧录进art中的问题，我当时也没有注意，具体你可以问一下Fredbill大佬
我的理解是axf文件包含调试信息，所以除了必要的机器码外，有一部分是不会烧录进入art的

**Comment by Y1ZzLu** [comment]
<img width="261" alt="screencut" src="https://github.com/Y1ZzLu/openart_fw_18th/assets/106618704/a41aca0c-ce56-4cb6-8199-f0251fa6ae42">
实际的大小应该是不会超出flash容量的，这是群里大佬的解释

**Comment by zhengbaiyang** [comment]
通过更改烧录文件安装位置，以及降低版本解决问题，多谢解答
