### ISSUE TITLE
关于固件二次开发

### ISSUE THREAD

**Issue by zhengbaiyang** [Y1ZzLu/openart_fw_18th#3]
大佬，我想要将只适用蓝底改为蓝底与黑底都适用，于是我在apriltag.c文件中在mylib_find_rects（）函数中加入一个判断hsv色域下对黑色的判断，也就是图片中的v>=0与v<=46，但此时将编译生成的axf文件烧录进openartmini并没有变化，为了验证是否有变化，我将下面判断蓝色的部分即h>=100,h<=124的部分注释后再烧录发现也没有变化，请问是我操作方式的不对还是修改位置不对呢
![屏幕截图 2024-04-18 205840](https://github.com/Y1ZzLu/openart_fw_18th/assets/109739963/b251b4a2-1745-4642-a770-ce8f234f7d21)

**Comment by Y1ZzLu** [comment]
修改之后编译烧录，可以在函数开头使用 mp_printf(&mp_plat_print, "build success!\n");
这样在openmv ide输出字符串提示，可以通过这种方式调试算法数据
